### ISSUE TITLE
OSX menu font

### ISSUE THREAD

**Issue by mpapis** [rvm/rvm-site#225] opened 2014-04-28 13:20 UTC
> matiaskorhonen> [09:22:20] Hey, the fonts in the navigation seem to be wonky on Chrome (OS X): http://s3itch.kiskolabs.net/RVM.io_fonts_20140428_102214.png
> matiaskorhonen> [09:23:06] The text looks all fuzzy and whatnot…
> matiaskorhonen> [09:27:22] I thibnk this might be because the URL to the woff/ttf/etc files on google fonts is hard coded in screen.css (instead of linking to the CSS that google provides). Since Google Fonts serves different files to different clients, the version that’s been linked to is probably sub-optimal for my browser.
> matiaskorhonen> [09:40:59] The 10px font size doesn’t help, but open sans does look a lot better even at that size on the Google Fonts preview page: http://s3itch.kiskolabs.net/Google_Fonts_20140428_102513_20140428_104020.png

**Comment by mpapis** [comment] 2015-02-19 22:11
ping

**Comment by havenwood** [comment] 2015-02-26 22:27
This looks fine on OS X with an updated version of Chrome. Closing since it looks like this was caused by one of the web font rendering bugs that has been fixed upstream.

**Closed by havenwood** 2015-02-26 22:27 UTC
